@startuml

skinparam monochrome true
skinparam handwritten true
left to right direction

actor Reader

rectangle SlicerPIRADS {
(load case)
(create case)
(save case)
(load case)
(study level assessment)
(add finding)
(lesion assessment)
(select measurement tool)
(segmentation)
(fiducial)
(ruler)
(identify lesion)
(generate report)
(select layout)
}

' regarding layouts
' sometimes not all sequences are available
' define rules when which layout should be available

(add finding) .> (lesion assessment) : include
(add finding) ..> (identify lesion) : include
(identify lesion) ..> (select measurement tool) : include
(select measurement tool) <.. (ruler) : extends
(select measurement tool) <.. (fiducial) : extends
(select measurement tool) <.. (segmentation) : extends


Reader -- (create case)
Reader -- (save case)
Reader -- (load case)
Reader -- (study level assessment)
Reader -- (add finding)
Reader -- (generate report)
Reader -- (select layout)

@enduml